import {ArrowUpRight,X} from 'lucide-react'
import {useEffect} from 'react'
type Language='ru'|'en'
export default function CloudMenu({language,onClose}:{language:Language;onClose:()=>void}){
 const ru=language==='ru'
 const items=ru?[['01','Маркетплейс','Услуги, цены и калькулятор','#marketplace'],['02','Портфолио','Проекты и продуктовые кейсы','#work'],['03','Услуги','Разработка и digital-системы','#services'],['04','Калькулятор','Рассчитать ориентировочную стоимость','#marketplace'],['05','Возможности','Что можем построить','#library'],['06','Экосистема','CORE / DEV / DIGITAL / PRODUCT','#ecosystem']]:[['01','Marketplace','Services, pricing and calculator','#marketplace'],['02','Portfolio','Projects and product cases','#work'],['03','Services','Development and digital systems','#services'],['04','Calculator','Estimate a project direction','#marketplace'],['05','Capabilities','What we can build','#library'],['06','Ecosystem','CORE / DEV / DIGITAL / PRODUCT','#ecosystem']]
 useEffect(()=>{const f=(e:KeyboardEvent)=>e.key==='Escape'&&onClose();addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[onClose])
 return <div className="cloud-menu-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><div className="cloud-menu" role="dialog" aria-modal="true"><div className="cloud-menu-head"><div><small>NEXUM / DIGITAL</small><h2>{ru?'Навигация по облаку':'Cloud navigation'}</h2></div><button onClick={onClose} aria-label="Close"><X/></button></div><div className="cloud-menu-grid">{items.map(([n,t,d,h])=><button key={n} onClick={()=>{onClose();location.hash=h.slice(1)}}><span>{n}</span><div><b>{t}</b><p>{d}</p></div><ArrowUpRight/></button>)}</div><div className="cloud-menu-foot"><span>CORE / DEV / DIGITAL / PRODUCT</span><i>{ru?'Выберите направление':'Choose a direction'}</i></div></div></div>
}
