import {ArrowUpRight} from 'lucide-react'
type Language='ru'|'en'
export default function DigitalCloud({language}:{language:Language}){
 const ru=language==='ru'
 return <div className="digital-cloud">
  <section className="cloud-hero" id="top">
   <div className="cloud-hero-copy"><div className="cloud-eyebrow"><span>NEXUM / DIGITAL</span><i>DIGITAL DEVELOPMENT CLOUD</i></div><h1>{ru?'Не сайт агентства.':'Not an agency site.'}<br/><em>{ru?'Цифровое облако.':'A digital cloud.'}</em></h1><p>{ru?'Пространство NEXUM для создания цифровых продуктов: разработка, AI, автоматизация, инфраструктура и собственные технологии.':'NEXUM space for building digital products: development, AI, automation, infrastructure and proprietary technology.'}</p><div className="cloud-hero-actions"><a href="#ecosystem" className="cloud-primary">{ru?'Исследовать систему':'Explore the system'} <ArrowUpRight size={17}/></a><a href="#start" className="cloud-secondary">{ru?'Начать проект':'Start a project'}</a></div><div className="cloud-hero-system"><div><span>01</span><b>CORE</b><small>{ru?'Интеллект':'Intelligence'}</small></div><div><span>02</span><b>DEV</b><small>{ru?'Разработка':'Build'}</small></div><div><span>03</span><b>DIGITAL</b><small>{ru?'Продукты':'Products'}</small></div><div><span>04</span><b>PRODUCT</b><small>{ru?'Запуск':'Launch'}</small></div></div></div>
   <div className="cloud-orbit" aria-hidden="true"><div className="hero-glass-panel hero-glass-panel-a"><small>01 / CORE</small><b>INTELLIGENCE</b><span>AI · MEMORY · MODELS</span></div><div className="hero-glass-panel hero-glass-panel-b"><small>02 / DEV</small><b>BUILD SYSTEM</b><span>CODE · PREVIEW · DEPLOY</span></div><div className="orbit-core"><span>N.</span><small>NEXUM</small><b>01—04</b></div><div className="orbit-line orbit-line-a"/><div className="orbit-line orbit-line-b"/><div className="orbit-line orbit-line-c"/><span className="orbit-chip chip-a">AI</span><span className="orbit-chip chip-b">WEB</span><span className="orbit-chip chip-c">APP</span><span className="orbit-chip chip-d">SAAS</span><span className="orbit-chip chip-e">DATA</span><div className="hero-glass-panel hero-glass-panel-c"><small>DIGITAL CLOUD</small><b>CONNECTED SYSTEM</b><span>CORE / DEV / PRODUCT</span></div></div>
  </section>
  <section className="cloud-intro"><div className="cloud-intro-index">00 / CLOUD</div><div><p>{ru?'NEXUM DIGITAL — презентационный слой экосистемы NEXUM.':'NEXUM DIGITAL — the presentation layer of the NEXUM ecosystem.'}</p><h2>{ru?<>Мы превращаем<br/><i>идеи в цифровые системы.</i></>:<>We turn ideas into<br/><i>digital systems.</i></>}</h2></div></section>
  <section className="cloud-map" id="ecosystem"><div className="cloud-section-head"><span>01 / ECOSYSTEM</span><p>{ru?'Как всё связано':'How it connects'}</p></div><div className="ecosystem-map ecosystem-glass-map"><div className="ecosystem-ambient ecosystem-ambient-a"/><div className="ecosystem-ambient ecosystem-ambient-b"/><div className="ecosystem-center"><b>NEXUM</b><span>{ru?'ТЕХНОЛОГИЧЕСКАЯ ЭКОСИСТЕМА':'TECHNOLOGY ECOSYSTEM'}</span><small>CORE / DEV / DIGITAL / PRODUCT</small></div><div className="ecosystem-node node-core"><strong>CORE</strong><span>Intelligence</span><small>AI · MEMORY · MODELS</small></div><div className="ecosystem-node node-dev"><strong>DEV</strong><span>Build</span><small>CODE · PREVIEW · DEPLOY</small></div><div className="ecosystem-node node-digital"><strong>DIGITAL</strong><span>Develop</span><small>DESIGN · SYSTEMS · WEB</small></div><div className="ecosystem-node node-gruzli"><strong>GRUZLI</strong><span>Product</span><small>MARKETPLACE · CRM · PWA</small></div><i className="eco-connector c1"/><i className="eco-connector c2"/><i className="eco-connector c3"/><i className="eco-connector c4"/></div></section>
  <section className="cloud-process" id="process"><div className="cloud-section-head"><span>02 / PROCESS</span><p>{ru?'Принцип работы':'How we work'}</p></div><div className="cloud-process-grid">{['DISCOVER','DESIGN','BUILD','CONNECT','LAUNCH','EVOLVE'].map((x,i)=><article key={x}><span>0{i+1}</span><b>{x}</b><em>{['01','02','03','04','05','06'][i]}</em><p>{ru?['Задача и контекст.','UX и визуальная система.','Код и продуктовая логика.','AI, API и интеграции.','Запуск и проверка.','Развитие и оптимизация.'][i]:['Problem and context.','UX and visual system.','Code and product logic.','AI, APIs and integrations.','Launch and validation.','Evolution and optimization.'][i]}</p><i className="process-glass-line"/></article>)}</div></section>
  <section className="cloud-cta" id="contact"><div><span>03 / START</span><h2>{ru?<>Что построим<br/><i>следующим?</i></>:<>What will we build<br/><i>next?</i></>}</h2></div><a href="#start">{ru?'Начать проект':'Start a project'} <ArrowUpRight/></a></section>
 </div>
}