import { Menu, X, Search, Command, ChevronDown } from 'lucide-react'
import { useEffect, useState } from 'react'
import type { Language } from './PlatformPages'

type Props = { language:Language; onLanguageChange:(language:Language)=>void; onOpenOS?:()=>void }

const nav = {
  ru:[['Услуги','#services'],['Solutions','#solutions'],['AI','#ai'],['Для бизнеса','#business']],
  en:[['Services','#services'],['Solutions','#solutions'],['AI','#ai'],['For business','#business']]
}

export default function Header({language,onLanguageChange,onOpenOS}:Props){
 const [open,setOpen]=useState(false),[search,setSearch]=useState(false),[query,setQuery]=useState(''),[more,setMore]=useState(false)
 const links=nav[language==='ru'?'ru':'en']
 useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);setSearch(false)}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearch(true)}};addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[])
 const go=(href:string)=>{setOpen(false);setMore(false);location.hash=href}
 const submit=(e:React.FormEvent)=>{e.preventDefault();setSearch(false);location.hash='#solutions?search='+encodeURIComponent(query)}
 return <><header className={open?'nxp-site-header open':''}><a className="nxp-brand" href="#" onClick={e=>{e.preventDefault();go('#')}}>NEXUM</a><nav className="nxp-main-nav">{links.map(([label,href])=><button key={href} onClick={()=>go(href)}>{label}</button>)}<button className="nxp-nav-more" onClick={()=>setMore(v=>!v)} aria-label="More"><ChevronDown size={14}/></button></nav>{more&&<div className="nxp-more-menu">{[['Experts','#experts'],['Pricing','#pricing'],['About','#about'],['Knowledge','#journal'],['Support','#support']].map(([label,href])=><button key={href} onClick={()=>{setMore(false);go(href)}}>{language==='ru'?({Experts:'Исполнители',Pricing:'Цены',About:'О компании',Knowledge:'Блог',Support:'Поддержка'} as Record<string,string>)[label]!:label}<span>↗</span></button>)}</div>}<div className="nxp-header-actions"><button className="nxp-header-search" onClick={()=>setSearch(true)}><Search size={16}/><span>{language==='ru'?'Поиск':'Search'}</span><kbd>⌘K</kbd></button>{onOpenOS&&<button className="nxp-os-trigger" onClick={onOpenOS}><Command size={15}/><span>NEXUM OS</span></button>}<div className="nxp-language"><button className={language==='ru'?'active':''} onClick={()=>onLanguageChange('ru')}>RU</button><span>/</span><button className={language==='en'?'active':''} onClick={()=>onLanguageChange('en')}>EN</button></div><button className="nxp-login-link" onClick={()=>go('#login')}>{language==='ru'?'Войти':'Log in'}</button><button className="nxp-header-cta" onClick={()=>go('#start')}>{language==='ru'?'Начать':'Get started'} <span>↗</span></button><button className="nxp-mobile-toggle" onClick={()=>setOpen(v=>!v)}>{open?<X/>:<Menu/>}</button></div></header>{open&&<div className="nxp-mobile-nav"><div>{links.map(([label,href])=><button key={href} onClick={()=>go(href)}>{label}<span>↗</span></button>)}</div><div className="nxp-mobile-secondary"><button onClick={()=>go('#experts')}>{language==='ru'?'Исполнители':'Experts'}</button><button onClick={()=>go('#pricing')}>{language==='ru'?'Цены':'Pricing'}</button><button onClick={()=>go('#journal')}>{language==='ru'?'Блог':'Knowledge'}</button><button onClick={()=>go('#support')}>{language==='ru'?'Поддержка':'Support'}</button></div></div>}{search&&<div className="nxp-search-layer" onMouseDown={e=>e.currentTarget===e.target&&setSearch(false)}><form className="nxp-global-search" onSubmit={submit}><div><Search size={19}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder={language==='ru'?'Искать услуги, проекты, AI, специалистов…':'Search services, projects, AI, experts…'}/><kbd>ESC</kbd></div><p>{language==='ru'?'Поиск ведёт в Solutions и будущий глобальный индекс NEXUM.':'Search feeds Solutions and the future NEXUM global index.'}</p><button className="nxp-button nxp-button-dark" type="submit">{language==='ru'?'Найти':'Search'} <Search size={15}/></button></form></div>}</>
}
