import {useMemo,useState} from 'react'
import {ArrowUpRight,Minus,Plus,X,Check} from 'lucide-react'
type Language='ru'|'en'
type Product={title:string;price:string;cat:string;description:string;includes:string[];time:string;options:string[];base:number}
export default function Marketplace({language}:{language:Language}){
 const ru=language==='ru'
 const products:Product[]=ru?[
  {title:'Сайт / Landing',price:'от 80 000 ₽',cat:'WEB',description:'Одностраничный продуктовый сайт с сильной визуальной системой и адаптивной версией.',includes:['UX / структура','UI-дизайн','Адаптивная разработка','Анимации','Публикация'],time:'от 7–14 дней',options:['Дополнительные страницы','CMS','Интеграции'],base:80000},
  {title:'Корпоративный сайт',price:'от 150 000 ₽',cat:'WEB',description:'Полноценный сайт компании с архитектурой контента, разделами и управляемой системой.',includes:['Аналитика и структура','UI-система','До 10 основных страниц','CMS / формы','SEO-база'],time:'от 14–30 дней',options:['Каталог','Личный кабинет','Мультиязычность'],base:150000},
  {title:'Web-приложение / SaaS',price:'от 300 000 ₽',cat:'PRODUCT',description:'Рабочее web-приложение с интерфейсом, логикой, ролями и интеграциями.',includes:['UX / product logic','Frontend','Backend','Авторизация','API'],time:'от 30 дней',options:['Платежи','CRM','Realtime','AI'],base:300000},
  {title:'AI-система / агент',price:'от 180 000 ₽',cat:'AI',description:'AI-функция, ассистент или агентный workflow под конкретную бизнес-задачу.',includes:['Архитектура AI','Prompt / logic layer','Интеграция модели','Knowledge / data layer','Тестирование'],time:'от 14–30 дней',options:['RAG','Tools','Memory','Local model'],base:180000},
  {title:'CRM / Dashboard',price:'от 220 000 ₽',cat:'SYSTEM',description:'Внутренняя система для управления данными, процессами, объектами и командами.',includes:['UX-сценарии','Dashboard','Роли и доступы','Фильтры / таблицы','API'],time:'от 21–45 дней',options:['Экспорт','Уведомления','AI-аналитика'],base:220000},
  {title:'Marketplace',price:'от 350 000 ₽',cat:'PLATFORM',description:'Двусторонняя или многосторонняя платформа с ролями, заказами и рабочими кабинетами.',includes:['Архитектура платформы','Каталог / лента','Роли','Чаты / заявки','Admin'],time:'от 45 дней',options:['Платежи','Геолокация','Рейтинги','Мобильный PWA'],base:350000}
 ]:[
  {title:'Landing website',price:'from €900',cat:'WEB',description:'A focused product website with a strong visual system and responsive experience.',includes:['UX / structure','UI design','Responsive build','Motion','Launch'],time:'from 7–14 days',options:['Extra pages','CMS','Integrations'],base:80000},
  {title:'Corporate website',price:'from €1,700',cat:'WEB',description:'A complete company website with structured content and a manageable system.',includes:['Analytics & structure','UI system','Up to 10 main pages','CMS / forms','SEO base'],time:'from 14–30 days',options:['Catalog','Account','Multilingual'],base:150000},
  {title:'Web app / SaaS',price:'from €3,400',cat:'PRODUCT',description:'A working web application with interface, logic, roles and integrations.',includes:['UX / product logic','Frontend','Backend','Auth','API'],time:'from 30 days',options:['Payments','CRM','Realtime','AI'],base:300000},
  {title:'AI system / agent',price:'from €2,000',cat:'AI',description:'An AI feature, assistant or agent workflow built around a concrete business task.',includes:['AI architecture','Prompt / logic layer','Model integration','Knowledge / data layer','Testing'],time:'from 14–30 days',options:['RAG','Tools','Memory','Local model'],base:180000},
  {title:'CRM / Dashboard',price:'from €2,500',cat:'SYSTEM',description:'An internal system for managing data, operations, objects and teams.',includes:['UX scenarios','Dashboard','Roles','Filters / tables','API'],time:'from 21–45 days',options:['Export','Notifications','AI analytics'],base:220000},
  {title:'Marketplace',price:'from €4,000',cat:'PLATFORM',description:'A multi-sided platform with roles, orders and dedicated workspaces.',includes:['Platform architecture','Catalog / feed','Roles','Chats / requests','Admin'],time:'from 45 days',options:['Payments','Geolocation','Ratings','Mobile PWA'],base:350000}
 ]
 const [type,setType]=useState(0),[pages,setPages]=useState(5),[complex,setComplex]=useState(1),[selected,setSelected]=useState<Product|null>(null),[extras,setExtras]=useState<string[]>([])
 const p=products[type]
 const extraPrices=ru?['CMS','AI','Платежи','Авторизация','Интеграции','Мобильная версия'].map((x,i)=>({name:x,value:[30000,60000,70000,45000,35000,50000][i]})):['CMS','AI','Payments','Auth','Integrations','Mobile'].map((x,i)=>({name:x,value:[350,650,750,500,400,550][i]}))
 const toggleExtra=(name:string)=>setExtras(v=>v.includes(name)?v.filter(x=>x!==name):[...v,name])
 const estimate=useMemo(()=>Math.max(0,p.base+(pages-5)*7000+(complex-1)*50000+extraPrices.filter(x=>extras.includes(x.name)).reduce((s,x)=>s+x.value,0)),[p,pages,complex,extras,extraPrices])
 return <section className="cloud-marketplace" id="marketplace">
  <div className="cloud-section-head"><span>08 / MARKETPLACE</span><p>{ru?'Услуги, цены и расчёт':'Services, pricing and estimate'}</p></div>
  <div className="market-grid">
   <div className="market-catalog">{products.map((item,i)=><button key={item.title} className={i===type?'active':''} onClick={()=>setType(i)}><small>{item.cat} / 0{i+1}</small><b>{item.title}</b><span>{item.price}</span><ArrowUpRight/></button>)}</div>
   <div className="market-calculator"><small>PROJECT ESTIMATOR</small><h3>{ru?'Калькулятор проекта':'Project calculator'}</h3><label>{ru?'Тип продукта':'Product type'}<select value={type} onChange={e=>setType(+e.target.value)}>{products.map((item,i)=><option value={i} key={item.title}>{item.title}</option>)}</select></label><label>{ru?'Количество экранов / страниц':'Screens / pages'}<div className="stepper"><button onClick={()=>setPages(Math.max(1,pages-1))}><Minus/></button><strong>{pages}</strong><button onClick={()=>setPages(Math.min(30,pages+1))}><Plus/></button></div></label><label>{ru?'Сложность':'Complexity'}<div className="complexity">{[1,2,3].map(v=><button key={v} className={complex===v?'active':''} onClick={()=>setComplex(v)}>{v}</button>)}</div></label><div className="market-extras"><small>{ru?'Дополнительные модули':'Add-ons'}</small>{extraPrices.map(x=><button type="button" key={x.name} className={extras.includes(x.name)?'active':''} onClick={()=>toggleExtra(x.name)}><span>{extras.includes(x.name)?<Check/>:<Plus/>}</span>{x.name}<em>{ru?'+'+x.value.toLocaleString('ru-RU')+' ₽':'+'+x.value+' €'}</em></button>)}</div><div className="market-total"><span>{ru?'Ориентир':'Estimate'}</span><b>{ru?estimate.toLocaleString('ru-RU')+' ₽':'€'+Math.round(estimate/90).toLocaleString('en-US')}</b></div><button className="market-details" onClick={()=>setSelected(p)}>{ru?'Подробнее об услуге':'Service details'} <ArrowUpRight/></button><a href={`#contact?service=${encodeURIComponent(p.title)}&estimate=${estimate}`}>{ru?'Заказать услугу':'Start this project'} <ArrowUpRight/></a><p>{ru?'Расчёт ориентировочный. Финальная смета зависит от задачи, интеграций и требований.':'Indicative estimate. Final scope depends on requirements, integrations and complexity.'}</p></div>
  </div>
  {selected&&<div className="market-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null)}}><div className="market-modal" role="dialog" aria-modal="true"><button className="market-modal-close" onClick={()=>setSelected(null)}><X/></button><div className="market-modal-head"><small>{selected.cat} / SERVICE</small><h2>{selected.title}</h2><strong>{selected.price}</strong><p>{selected.description}</p></div><div className="market-modal-body"><div><small>{ru?'В комплекте':'Included'}</small><ul>{selected.includes.map(x=><li key={x}>{x}</li>)}</ul></div><div><small>{ru?'Срок':'Timeline'}</small><p>{selected.time}</p><small>{ru?'Дополнительно':'Options'}</small><ul>{selected.options.map(x=><li key={x}>{x}</li>)}</ul></div></div><a href="#contact" onClick={()=>setSelected(null)}>{ru?'Обсудить проект':'Start a project'} <ArrowUpRight/></a></div></div>}
 </section>
}
