import {useEffect,useRef,useState} from 'react'
import {ArrowRight,ArrowUpRight,Check,ChevronDown,Plus,Star,X} from 'lucide-react'
import type {Language} from './Header'
type Service={id:string;title:string;ru:string;desc:string;ruDesc:string;tag:string}
const services:Service[]=[
{id:'web',title:'Websites & platforms',ru:'Сайты и платформы',desc:'High-end websites, landing pages and digital platforms.',ruDesc:'Сайты, лендинги и цифровые платформы с сильной подачей.',tag:'WEB'},
{id:'app',title:'Web & mobile apps',ru:'Web и мобильные приложения',desc:'Product interfaces, SaaS, marketplaces and mobile experiences.',ruDesc:'Продуктовые интерфейсы, SaaS, маркетплейсы и приложения.',tag:'PRODUCT'},
{id:'ai',title:'AI systems',ru:'AI-системы',desc:'AI assistants, agents, knowledge systems and automation.',ruDesc:'AI-ассистенты, агенты, knowledge-системы и автоматизация.',tag:'AI'},
{id:'design',title:'UI/UX & branding',ru:'UI/UX и брендинг',desc:'Design systems, identity and product experience.',ruDesc:'Дизайн-системы, айдентика и продуктовый опыт.',tag:'DESIGN'},
{id:'motion',title:'3D & motion',ru:'3D и motion',desc:'Product visualisation, 3D scenes and motion design.',ruDesc:'3D-визуализации, сцены и motion-дизайн.',tag:'CREATIVE'},
{id:'business',title:'Business automation',ru:'Автоматизация бизнеса',desc:'CRM, internal tools, integrations and workflows.',ruDesc:'CRM, внутренние системы, интеграции и рабочие процессы.',tag:'BUSINESS'}]
const projects=[['01','NEXUM AI','AI platform','AI-платформа','AI workspace and agent infrastructure.','AI-рабочая среда и инфраструктура агентов.','AI'],['02','GRUZLI','Marketplace','Маркетплейс','A service marketplace connecting clients, dispatchers and teams.','Система, соединяющая заказчиков, диспетчеров и команды.','PRODUCT'],['03','DIGITAL CLOUD','Digital studio','Цифровая студия','A premium digital service experience.','Премиальный цифровой сервис и коммерческий сайт.','WEB']]
const reviews=[['Антон','Основатель продукта','NEXUM помог собрать не просто сайт, а понятную систему вокруг продукта.','NEXUM helped us build a system around the product, not just a website.'],['Мария','CEO','Сильная работа с логикой, интерфейсом и деталями.','Strong work across product logic, interface and details.'],['Дмитрий','Product lead','Быстро прошли путь от идеи до рабочего прототипа.','We moved from idea to a working prototype quickly.']]
const ru=(l:Language)=>l==='ru'
function go(h:string){location.hash=h}
function Art({tag}:{tag:string}){return <div className="nx-art"><span>{tag}</span><div className="nx-art-orbit"/><div className="nx-art-window"><i/><i/><i/><b>{tag}</b><small>01 / NEXUM SYSTEM</small></div></div>}
function Home({language}:{language:Language}){const r=ru(language);return <main>
<section className="nx-hero"><div><small> NEXUM / DIGITAL STUDIO</small><h1>{r?<>Создаём<br/><em>цифровые продукты.</em></>:<>We build<br/><em>digital products.</em></>}</h1><p>{r?'Сайты, приложения, AI и автоматизация — проектируем и запускаем как единый продукт.':'Websites, apps, AI and automation — designed and shipped as one product.'}</p><div className="nx-actions"><button className="nx-btn dark" onClick={()=>go('#start')}>{r?'Обсудить проект':'Start a project'} <ArrowUpRight/></button><button className="nx-btn" onClick={()=>go('#services')}>{r?'Смотреть услуги':'View services'} <ArrowRight/></button></div></div><Art tag="DIGITAL"/></section>
<section className="nx-strip"><span>WEB</span><span>AI</span><span>PRODUCT</span><span>DESIGN</span><span>3D</span><span>AUTOMATION</span></section>
<Services language={language}/><Projects language={language}/><Reviews language={language}/>
<section className="nx-cta"><small>04 / START</small><h2>{r?<>Есть задача?<br/><em>Давайте соберём.</em></>:<>Have a brief?<br/><em>Let's build it.</em></>}</h2><button className="nx-btn dark" onClick={()=>go('#start')}>{r?'Начать проект':'Start a project'} <ArrowUpRight/></button></section>
</main>}
function Services({language}:{language:Language}){const r=ru(language);return <section id="services" className="nx-section"><div className="nx-head"><div><small>01 / SERVICES</small><h2>{r?<>Услуги,<br/><em>которые работают.</em></>:<>Services<br/><em>that ship.</em></>}</h2></div><p>{r?'От стратегии и дизайна до разработки и AI. Один продуктовый контур.':'Strategy, design, engineering and AI in one product workflow.'}</p></div><div className="nx-service-grid">{services.map((s,i)=><button key={s.id} onClick={()=>go('#service/'+s.id)}><span>0{i+1} / {s.tag}</span><strong>{r?s.ru:s.title}</strong><p>{r?s.ruDesc:s.desc}</p><ArrowUpRight/></button>)}</div></section>}
function Projects({language}:{language:Language}){const r=ru(language);return <section id="projects" className="nx-section projects"><div className="nx-head"><div><small>02 / PROJECTS</small><h2>{r?<>Работы,<br/><em>которые можно показать.</em></>:<>Selected<br/><em>products.</em></>}</h2></div><p>{r?'Реальные направления NEXUM и продуктовые концепции без выдуманных метрик.':'NEXUM products and concepts, without fabricated metrics.'}</p></div><div className="nx-project-grid">{projects.map((p,i)=><button key={p[0]} onClick={()=>go('#project/'+p[0])}><Art tag={p[6]}/><div><small>{p[0]} / {p[2]}</small><h3>{r?p[3]:p[1]}</h3><p>{r?p[5]:p[4]}</p><span>{r?'Открыть проект':'Open project'} <ArrowUpRight size={14}/></span></div></button>)}</div></section>}
function Reviews({language}:{language:Language}){const r=ru(language);return <section id="reviews" className="nx-section"><div className="nx-head"><div><small>03 / REVIEWS</small><h2>{r?<>Что говорят<br/><em>о работе с NEXUM.</em></>:<>What clients<br/><em>say about NEXUM.</em></>}</h2></div></div><div className="nx-reviews">{reviews.map((x,i)=><article key={i}><div>{[1,2,3,4,5].map(n=><Star key={n} size={13} fill="currentColor"/>)}</div><p>“{r?x[2]:x[3]}”</p><strong>{x[0]}</strong><small>{x[1]}</small></article>)}</div></section>}
function ServicePage({language,id}:{language:Language;id:string}){const r=ru(language),s=services.find(x=>x.id===id);if(!s)return <NotFound language={language}/>;return <main className="nx-detail"><button onClick={()=>go('#services')} className="nx-back">← {r?'Все услуги':'All services'}</button><div className="nx-detail-grid"><div><small>{s.tag} / SERVICE</small><h1>{r?s.ru:s.title}</h1><p>{r?s.ruDesc:s.desc}</p><button className="nx-btn dark" onClick={()=>go('#start')}>{r?'Заказать':'Start'} <ArrowUpRight/></button></div><Art tag={s.tag}/></div><div className="nx-process">{[['01','DISCOVER',r?'Фиксируем задачу и результат':'Frame the outcome'],['02','DESIGN',r?'Проектируем сценарий и интерфейс':'Design the flow and interface'],['03','BUILD',r?'Разрабатываем и интегрируем':'Build and integrate'],['04','LAUNCH',r?'Проверяем и запускаем':'QA and launch']].map(x=><article key={x[0]}><b>{x[0]}</b><strong>{x[1]}</strong><span>{x[2]}</span><Check/></article>)}</div></main>}
function ProjectPage({language,id}:{language:Language;id:string}){const r=ru(language),p=projects.find(x=>x[0]===id);if(!p)return <NotFound language={language}/>;return <main className="nx-detail"><button onClick={()=>go('#projects')} className="nx-back">← {r?'Все проекты':'All projects'}</button><div className="nx-detail-grid"><div><small>{p[6]} / PROJECT</small><h1>{p[1]}</h1><p>{r?p[5]:p[4]}</p><button className="nx-btn dark" onClick={()=>go('#start')}>{r?'Обсудить похожий проект':'Discuss a similar project'} <ArrowUpRight/></button></div><Art tag={p[6]}/></div><div className="nx-project-info"><span><b>TYPE</b>{p[2]}</span><span><b>ROLE</b>NEXUM Studio</span><span><b>STATUS</b>Selected case</span></div></main>}
function Auth({language,mode}:{language:Language;mode:'login'|'register'}){const r=ru(language),[done,setDone]=useState(false);return <main className="nx-auth"><div className="nx-auth-card"><small> NEXUM / ACCOUNT</small><h1>{mode==='login'?(r?'С возвращением.':'Welcome back.'):(r?'Создать аккаунт.':'Create your account.')}</h1><p>{mode==='login'?(r?'Войдите в рабочий контур NEXUM.':'Sign in to your NEXUM workspace.'):(r?'Регистрация для клиентов и команд.':'Create an account for clients and teams.')}</p>{done?<div className="nx-auth-done"><Check/><b>{r?'Готово.':'Done.'}</b><span>{r?'Демо-режим: аккаунт создан локально.':'Demo mode: account created locally.'}</span></div>:<form onSubmit={e=>{e.preventDefault();setDone(true)}}><label>{r?'Имя':'Name'}{mode==='login'?'':' *'}<input required={mode==='register'} placeholder={r?'Ваше имя':'Your name'}/></label><label>Email<input type="email" required placeholder="you@example.com"/></label><label>{r?'Пароль':'Password'}<input type="password" required minLength={6}/></label>{mode==='register'&&<label className="nx-check"><input type="checkbox" required/> {r?'Я принимаю условия':'I accept the terms'}</label>}<button className="nx-btn dark" type="submit">{mode==='login'?(r?'Войти':'Log in'):(r?'Зарегистрироваться':'Create account')} <ArrowRight/></button></form>}<button className="nx-switch" onClick={()=>go(mode==='login'?'#register':'#login')}>{mode==='login'?(r?'Нет аккаунта? Регистрация':'Need an account? Register'):(r?'Уже есть аккаунт? Войти':'Already have an account? Log in')}</button></div></main>}
function Start({language}:{language:Language}){const r=ru(language),[sent,setSent]=useState(false);return <main className="nx-start-page"><div><small> NEXUM / START A PROJECT</small><h1>{r?<>Расскажите<br/><em>о задаче.</em></>:<>Tell us<br/><em>about the brief.</em></>}</h1><p>{r?'Опишите цель, продукт и желаемый результат. Мы вернёмся с понятным следующим шагом.':'Tell us the goal, product and desired outcome. We will return with a clear next step.'}</p></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent?<div className="nx-sent"><Check/><h2>{r?'Заявка отправлена.':'Brief sent.'}</h2><p>{r?'Мы получили запрос.':'We received your brief.'}</p></div>:<><label>{r?'Имя':'Name'}<input required/></label><label>Email<input type="email" required/></label><label>{r?'Задача':'Brief'}<textarea required rows={7}/></label><button className="nx-btn dark" type="submit">{r?'Отправить':'Send brief'} <ArrowUpRight/></button></>}</form></main>}

function DemoSite({type}:{type:string}) {
  if (type === 'commerce') return <CommerceDemo />;
  if (type === 'ai') return <AIDemo />;
  if (type === 'bot') return <BotDemo />;
  if (type === 'product') return <ProductDemo />;
  return <MiniGame />;
}
function DemoFrame({children,className}:{children:any;className:string}) {
  return <div className={'pf-demo '+className}>{children}</div>;
}
function CommerceDemo() {
  const [cart,setCart]=useState(0);
  return <DemoFrame className="pf-commerce"><div className="pf-demo-top"><span>NEXUM STORE</span><button type="button" onClick={()=>setCart(cart+1)}>CART / {cart}</button></div><div className="pf-commerce-main"><small>OBJECTS / 2026</small><h3>Objects<br/><em>with a pulse.</em></h3><div className="pf-orb-product"></div><button type="button" onClick={()=>setCart(cart+1)}>ADD TO CART <ArrowUpRight size={13}/></button></div></DemoFrame>;
}
function AIDemo() {
  const [running,setRunning]=useState(false);
  return <DemoFrame className="pf-ai"><div className="pf-demo-top"><span>AI CORE / ONLINE</span><span>LIVE</span></div><div className="pf-ai-nav"><b>NEXUM AI</b><button type="button" onClick={()=>setRunning(!running)}>{running?'STOP':'NEW TASK'}</button></div><div className="pf-ai-center"><div className="pf-ai-orb"></div><small>{running?'AGENT IS WORKING':'READY FOR INSTRUCTION'}</small><h3>{running?'Building your interface...':'Ask. Build. Ship.'}</h3><div className="pf-ai-stream"><span>{running?'Generating components':'Try: Create a landing page'}</span></div></div></DemoFrame>;
}
function BotDemo() {
  const [messages,setMessages]=useState(0);
  return <DemoFrame className="pf-bot"><div className="pf-demo-top"><span>TELEGRAM / SERVICE</span><span>ONLINE</span></div><div className="pf-bot-head"><div className="pf-avatar">N</div><div><b>NEXUM Service</b><small>online - 24/7</small></div></div><div className="pf-chat"><span>Hello. Where do you need a team?</span><b>Moscow - Khimki / tomorrow 10:00</b>{messages>0&&<span>Suitable options found.</span>}</div><div className="pf-bot-actions"><button type="button" onClick={()=>setMessages(messages+1)}>FIND TEAM</button><button type="button" onClick={()=>setMessages(messages+1)}>ORDER STATUS</button></div></DemoFrame>;
}
function ProductDemo() {
  const [tab,setTab]=useState('home');
  const title=tab==='home'?'Project control':tab==='data'?'Live analytics':'Team workspace';
  return <DemoFrame className="pf-product-app"><div className="pf-demo-top"><span>NEXUM / PRODUCT</span><span>COMMAND</span></div><div className="pf-app-body"><aside><b>N</b>{['home','data','team'].map(item=><button type="button" key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item.slice(0,1).toUpperCase()}</button>)}</aside><section><small>WORKSPACE / {tab.toUpperCase()}</small><h3>{title}</h3><div className="pf-metrics"><i></i><i></i><i></i></div><div className="pf-chart"><span></span><span></span><span></span><span></span><span></span></div></section></div></DemoFrame>;
}
function MiniGame() {
  const [active,setActive]=useState(false);
  return <DemoFrame className="pf-mini-game"><div className="pf-demo-top"><span>NEXUM ARCADE</span><button type="button" onClick={()=>setActive(true)}>{active?'RUNNING':'PLAY'}</button></div><div className="pf-game-sim">{active?<><span className="pf-game-ball"></span><span className="pf-game-paddle"></span></>:<strong>PRESS PLAY</strong>}</div></DemoFrame>;
}
function Arkanoid({language}:{language:Language}) {
  const [running,setRunning]=useState(false);
  const start=()=>setRunning(true);
  return <div className="pf-game-box"><div className="pf-game-head"><span>ARKANOID / NEXUM</span><b>LIVE</b></div><div className="pf-game-sim">{running?<><span className="pf-game-ball"></span><span className="pf-game-paddle"></span></>:<strong>{language==='ru'?'ГОТОВО К ИГРЕ':'READY TO PLAY'}</strong>}</div><div className="pf-game-controls"><span>{language==='ru'?'Интерактивный demo':'Interactive demo'}</span><button type="button" onClick={start}>{running?(language==='ru'?'ИГРА ИДЁТ':'RUNNING'):(language==='ru'?'ИГРАТЬ':'PLAY')} <ArrowRight size={14}/></button></div></div>;
}
function PortfolioDetail({language,id}:{language:Language;id:string}){const r=ru(language),item=portfolioItems.find(x=>x.id===id);if(!item)return <NotFound language={language}/>;return <main className="nx-detail pf-detail"><button onClick={()=>go('#portfolio')} className="nx-back">← {r?'Портфолио':'Portfolio'}</button><div className="nx-detail-grid"><div><small>{item.kind} / INTERACTIVE CASE</small><h1>{r?item.ru:item.title}</h1><p>{r?item.ruDesc:item.desc}</p><button className="nx-btn dark" onClick={()=>go('#start')}>{r?'Сделать похожий':'Build something similar'} <ArrowUpRight/></button></div><DemoSite type={item.type}/></div></main>}
\nfunction NotFound({language}:{language:Language}){return <main className="nx-auth"><div className="nx-auth-card"><small>404</small><h1>{ru(language)?'Не найдено':'Not found'}</h1><button className="nx-btn dark" onClick={()=>go('#')}>NEXUM <ArrowRight/></button></div></main>}
export default function PlatformRouter({language}:{language:Language}){const p=(location.hash||'#').split('?')[0];if(p==='#'||p==='')return <Home language={language}/>;if(p==='#services')return <Services language={language}/>;if(p==='#projects')return <Projects language={language}/>;if(p==='#reviews')return <Reviews language={language}/>;if(p==='#portfolio')return <Portfolio language={language}/>;if(p.startsWith('#portfolio/'))return <PortfolioDetail language={language} id={p.split('/')[1]||''}/>;if(p==='#start')return <Start language={language}/>;if(p==='#login'||p==='#register')return <Auth language={language} mode={p==='#login'?'login':'register'}/>;if(p.startsWith('#service/'))return <ServicePage language={language} id={p.split('/')[1]||''}/>;if(p.startsWith('#project/'))return <ProjectPage language={language} id={p.split('/')[1]||''}/>;return <NotFound language={language}/>}
