import {useEffect,useRef,useState} from 'react'
import {ArrowRight,ArrowUpRight,Check,ChevronDown,Plus,Star,X} from 'lucide-react'
import type {Language} from './Header'
type Service={id:string;title:string;ru:string;desc:string;ruDesc:string;tag:string}
const services:Service[]=[
{id:'web',title:'Websites & platforms',ru:'Сайты и платформы',desc:'High-end websites, landing pages and digital platforms.',ruDesc:'Сайты, лендинги и цифровые платформы с сильной подачей.',tag:'WEB'},
{id:'app',title:'Web & mobile apps',ru:'Web и мобильные приложения',desc:'Product interfaces, SaaS, marketplaces and mobile experiences.',ruDesc:'Продуктовые интерфейсы, SaaS, маркетплейсы и приложения.',tag:'PRODUCT'},
{id:'ai',title:'AI systems',ru:'AI-системы',desc:'AI assistants, agents, knowledge systems and automation.',ruDesc:'AI-ассистенты, агенты, knowledge-системы и автоматизация.',tag:'AI'},
{id:'design',title:'UI/UX & branding',ru:'UI/UX и брендинг',desc:'Design systems, identity and product experience.',ruDesc:'Дизайн-системы, айдентика и продуктовый опыт.',tag:'DESIGN'},
{id:'motion',title:'3D & motion',ru:'3D и motion',desc:'Product visualisation, 3D scenes and motion design.',ruDesc:'3D-визуализации, сцены и motion-дизайн.',tag:'CREATIVE'},
{id:'business',title:'Business automation',ru:'Автоматизация бизнеса',desc:'CRM, internal tools, integrations and workflows.',ruDesc:'CRM, внутренние системы, интеграции и рабочие процессы.',tag:'BUSINESS'}]
const projects=[['01','NEXUM AI','AI platform','AI-платформа','AI workspace and agent infrastructure.','AI-рабочая среда и инфраструктура агентов.','AI'],['02','GRUZLI','Marketplace','Маркетплейс','A service marketplace connecting clients, dispatchers and teams.','Система, соединяющая заказчиков, диспетчеров и команды.','PRODUCT'],['03','DIGITAL CLOUD','Digital studio','Цифровая студия','A premium digital service experience.','Премиальный цифровой сервис и коммерческий сайт.','WEB']]
const reviews=[['Антон','Основатель продукта','NEXUM помог собрать не просто сайт, а понятную систему вокруг продукта.','NEXUM helped us build a system around the product, not just a website.'],['Мария','CEO','Сильная работа с логикой, интерфейсом и деталями.','Strong work across product logic, interface and details.'],['Дмитрий','Product lead','Быстро прошли путь от идеи до рабочего прототипа.','We moved from idea to a working prototype quickly.']]
const ru=(l:Language)=>l==='ru'
function go(h:string){location.hash=h}
function Art({tag}:{tag:string}){return <div className="nx-art"><span>{tag}</span><div className="nx-art-orbit"/><div className="nx-art-window"><i/><i/><i/><b>{tag}</b><small>01 / NEXUM SYSTEM</small></div></div>}
function Home({language}:{language:Language}){const r=ru(language);return <main>
<section className="nx-hero"><div><small> NEXUM / DIGITAL STUDIO</small><h1>{r?<>Создаём<br/><em>цифровые продукты.</em></>:<>We build<br/><em>digital products.</em></>}</h1><p>{r?'Сайты, приложения, AI и автоматизация — проектируем и запускаем как единый продукт.':'Websites, apps, AI and automation — designed and shipped as one product.'}</p><div className="nx-actions"><button className="nx-btn dark" onClick={()=>go('#start')}>{r?'Обсудить проект':'Start a project'} <ArrowUpRight/></button><button className="nx-btn" onClick={()=>go('#services')}>{r?'Смотреть услуги':'View services'} <ArrowRight/></button></div></div><Art tag="DIGITAL"/></section>
<section className="nx-strip"><span>WEB</span><span>AI</span><span>PRODUCT</span><span>DESIGN</span><span>3D</span><span>AUTOMATION</span></section>
<Services language={language}/><Projects language={language}/><Reviews language={language}/>
<section className="nx-cta"><small>04 / START</small><h2>{r?<>Есть задача?<br/><em>Давайте соберём.</em></>:<>Have a brief?<br/><em>Let's build it.</em></>}</h2><button className="nx-btn dark" onClick={()=>go('#start')}>{r?'Начать проект':'Start a project'} <ArrowUpRight/></button></section>
</main>}
function Services({language}:{language:Language}){const r=ru(language);return <section id="services" className="nx-section"><div className="nx-head"><div><small>01 / SERVICES</small><h2>{r?<>Услуги,<br/><em>которые работают.</em></>:<>Services<br/><em>that ship.</em></>}</h2></div><p>{r?'От стратегии и дизайна до разработки и AI. Один продуктовый контур.':'Strategy, design, engineering and AI in one product workflow.'}</p></div><div className="nx-service-grid">{services.map((s,i)=><button key={s.id} onClick={()=>go('#service/'+s.id)}><span>0{i+1} / {s.tag}</span><strong>{r?s.ru:s.title}</strong><p>{r?s.ruDesc:s.desc}</p><ArrowUpRight/></button>)}</div></section>}
function Projects({language}:{language:Language}){const r=ru(language);return <section id="projects" className="nx-section projects"><div className="nx-head"><div><small>02 / PROJECTS</small><h2>{r?<>Работы,<br/><em>которые можно показать.</em></>:<>Selected<br/><em>products.</em></>}</h2></div><p>{r?'Реальные направления NEXUM и продуктовые концепции без выдуманных метрик.':'NEXUM products and concepts, without fabricated metrics.'}</p></div><div className="nx-project-grid">{projects.map((p,i)=><button key={p[0]} onClick={()=>go('#project/'+p[0])}><Art tag={p[6]}/><div><small>{p[0]} / {p[2]}</small><h3>{r?p[3]:p[1]}</h3><p>{r?p[5]:p[4]}</p><span>{r?'Открыть проект':'Open project'} <ArrowUpRight size={14}/></span></div></button>)}</div></section>}
function Reviews({language}:{language:Language}){const r=ru(language);return <section id="reviews" className="nx-section"><div className="nx-head"><div><small>03 / REVIEWS</small><h2>{r?<>Что говорят<br/><em>о работе с NEXUM.</em></>:<>What clients<br/><em>say about NEXUM.</em></>}</h2></div></div><div className="nx-reviews">{reviews.map((x,i)=><article key={i}><div>{[1,2,3,4,5].map(n=><Star key={n} size={13} fill="currentColor"/>)}</div><p>“{r?x[2]:x[3]}”</p><strong>{x[0]}</strong><small>{x[1]}</small></article>)}</div></section>}
function ServicePage({language,id}:{language:Language;id:string}){const r=ru(language),s=services.find(x=>x.id===id);if(!s)return <NotFound language={language}/>;return <main className="nx-detail"><button onClick={()=>go('#services')} className="nx-back">← {r?'Все услуги':'All services'}</button><div className="nx-detail-grid"><div><small>{s.tag} / SERVICE</small><h1>{r?s.ru:s.title}</h1><p>{r?s.ruDesc:s.desc}</p><button className="nx-btn dark" onClick={()=>go('#start')}>{r?'Заказать':'Start'} <ArrowUpRight/></button></div><Art tag={s.tag}/></div><div className="nx-process">{[['01','DISCOVER',r?'Фиксируем задачу и результат':'Frame the outcome'],['02','DESIGN',r?'Проектируем сценарий и интерфейс':'Design the flow and interface'],['03','BUILD',r?'Разрабатываем и интегрируем':'Build and integrate'],['04','LAUNCH',r?'Проверяем и запускаем':'QA and launch']].map(x=><article key={x[0]}><b>{x[0]}</b><strong>{x[1]}</strong><span>{x[2]}</span><Check/></article>)}</div></main>}
function ProjectPage({language,id}:{language:Language;id:string}){const r=ru(language),p=projects.find(x=>x[0]===id);if(!p)return <NotFound language={language}/>;return <main className="nx-detail"><button onClick={()=>go('#projects')} className="nx-back">← {r?'Все проекты':'All projects'}</button><div className="nx-detail-grid"><div><small>{p[6]} / PROJECT</small><h1>{p[1]}</h1><p>{r?p[5]:p[4]}</p><button className="nx-btn dark" onClick={()=>go('#start')}>{r?'Обсудить похожий проект':'Discuss a similar project'} <ArrowUpRight/></button></div><Art tag={p[6]}/></div><div className="nx-project-info"><span><b>TYPE</b>{p[2]}</span><span><b>ROLE</b>NEXUM Studio</span><span><b>STATUS</b>Selected case</span></div></main>}
function Auth({language,mode}:{language:Language;mode:'login'|'register'}){const r=ru(language),[done,setDone]=useState(false);return <main className="nx-auth"><div className="nx-auth-card"><small> NEXUM / ACCOUNT</small><h1>{mode==='login'?(r?'С возвращением.':'Welcome back.'):(r?'Создать аккаунт.':'Create your account.')}</h1><p>{mode==='login'?(r?'Войдите в рабочий контур NEXUM.':'Sign in to your NEXUM workspace.'):(r?'Регистрация для клиентов и команд.':'Create an account for clients and teams.')}</p>{done?<div className="nx-auth-done"><Check/><b>{r?'Готово.':'Done.'}</b><span>{r?'Демо-режим: аккаунт создан локально.':'Demo mode: account created locally.'}</span></div>:<form onSubmit={e=>{e.preventDefault();setDone(true)}}><label>{r?'Имя':'Name'}{mode==='login'?'':' *'}<input required={mode==='register'} placeholder={r?'Ваше имя':'Your name'}/></label><label>Email<input type="email" required placeholder="you@example.com"/></label><label>{r?'Пароль':'Password'}<input type="password" required minLength={6}/></label>{mode==='register'&&<label className="nx-check"><input type="checkbox" required/> {r?'Я принимаю условия':'I accept the terms'}</label>}<button className="nx-btn dark" type="submit">{mode==='login'?(r?'Войти':'Log in'):(r?'Зарегистрироваться':'Create account')} <ArrowRight/></button></form>}<button className="nx-switch" onClick={()=>go(mode==='login'?'#register':'#login')}>{mode==='login'?(r?'Нет аккаунта? Регистрация':'Need an account? Register'):(r?'Уже есть аккаунт? Войти':'Already have an account? Log in')}</button></div></main>}
function Start({language}:{language:Language}){const r=ru(language),[sent,setSent]=useState(false);return <main className="nx-start-page"><div><small> NEXUM / START A PROJECT</small><h1>{r?<>Расскажите<br/><em>о задаче.</em></>:<>Tell us<br/><em>about the brief.</em></>}</h1><p>{r?'Опишите цель, продукт и желаемый результат. Мы вернёмся с понятным следующим шагом.':'Tell us the goal, product and desired outcome. We will return with a clear next step.'}</p></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent?<div className="nx-sent"><Check/><h2>{r?'Заявка отправлена.':'Brief sent.'}</h2><p>{r?'Мы получили запрос.':'We received your brief.'}</p></div>:<><label>{r?'Имя':'Name'}<input required/></label><label>Email<input type="email" required/></label><label>{r?'Задача':'Brief'}<textarea required rows={7}/></label><button className="nx-btn dark" type="submit">{r?'Отправить':'Send brief'} <ArrowUpRight/></button></>}</form></main>}

function DemoSite({type}:{type:string}){return <div className="pf-demo"><div className="pf-demo-top"><span>NEXUM DEMO</span><span>● ● ●</span></div>{type==='commerce'?<><div className="pf-demo-hero"><small>NEW COLLECTION / 2026</small><b>Objects<br/><em>with a pulse.</em></b><div className="pf-product"><div className="pf-product-shape"/></div></div><div className="pf-demo-row"><i/><i/><i/></div></>:type==='ai'?<><div className="pf-ai-orb"/><div className="pf-ai-copy"><small>AI SYSTEM / ONLINE</small><b>Ask. Build.<br/><em>Ship.</em></b><span>Context-aware agent workspace</span></div><div className="pf-ai-bars"><i/><i/><i/><i/></div></>:<><div className="pf-bot-head"><div className="pf-avatar">G</div><div><b>GRUZLI BOT</b><small>online · 24/7</small></div></div><div className="pf-chat"><span>Привет! Куда нужна команда?</span><b>Москва → Химки · завтра 10:00</b><span>Нашёл 4 подходящих варианта.</span></div><div className="pf-chat-input">Написать сообщение… <strong>↑</strong></div></>}</div>}
const portfolioItems=[
 {id:'fashion',kind:'WEB',title:'Editorial commerce',ru:'Анимационный интернет-магазин',desc:'Cinematic storefront with motion, product focus and editorial storytelling.',ruDesc:'Кинематографичный магазин с motion, фокусом на продукте и editorial-подачей.',type:'commerce'},
 {id:'ai-showcase',kind:'AI',title:'AI product workspace',ru:'AI-продукт с агентом',desc:'Interactive AI workspace concept with live system states and assistant flow.',ruDesc:'Интерактивная AI-среда с состояниями системы и потоком агента.',type:'ai'},
 {id:'telegram',kind:'BOT',title:'Telegram service bot',ru:'Telegram-бот сервиса',desc:'Animated customer flow: request, matching, status and communication.',ruDesc:'Анимированный клиентский сценарий: заявка, подбор, статус и чат.',type:'bot'},
]
function Portfolio({language}:{language:Language}){const r=ru(language);return <main className="nx-portfolio"><section className="pf-hero"><div><small>04 / PORTFOLIO LAB</small><h1>{r?<>Сначала<br/><em>показываем.</em></>:<>See it<br/><em>in motion.</em>}</h1><p>{r?'Не статичные картинки. Здесь можно потрогать подход NEXUM: сайты, AI-интерфейсы, Telegram-боты и интерактивные продукты.':'Not static screenshots. Explore NEXUM through animated sites, AI interfaces, Telegram bots and interactive products.'}</p></div><div className="pf-score"><span>BUILD QUALITY</span><strong>LIVE</strong><small>{r?'Интерактивные демо':'Interactive demos'}</small></div></section><section className="pf-grid">{portfolioItems.map(item=><article key={item.id} className="pf-card"><DemoSite type={item.type}/><div className="pf-card-copy"><div><small>{item.kind} / DEMO</small><h2>{r?item.ru:item.title}</h2><p>{r?item.ruDesc:item.desc}</p></div><button onClick={()=>location.hash='#portfolio/'+item.id}>Open <ArrowUpRight size={15}/></button></div></article>)}</section><section className="pf-game"><div><small>05 / INTERACTIVE LAB</small><h2>{r?<>Проверьте<br/><em>сайт в игре.</em></>:<>Test the<br/><em>experience.</em>}</h2><p>{r?'Арканоид — маленькая демонстрация того, что мы делаем не только красивую оболочку. Здесь есть реальное состояние, анимация, управление и игровой цикл.':'Arkanoid is a small proof that the interface is not just a screenshot: it has state, animation, input and a real game loop.'}</p></div><Arkanoid language={language}/></section></main>}
function Arkanoid({language}:{language:Language}){const canvasRef=useRef<HTMLCanvasElement>(null);const [score,setScore]=useState(0);const [running,setRunning]=useState(false);const gameRef=useRef<{running:boolean;score:number}>({running:false,score:0});useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;const W=360,H=260;let x=180,y=220,vx=3,vy=-3,paddle=180,raf=0;const bricks=Array.from({length:28},()=>true);const keys={left:false,right:false};const onKey=(e:KeyboardEvent,down:boolean)=>{if(e.key==='ArrowLeft')keys.left=down;if(e.key==='ArrowRight')keys.right=down};const onMove=(e:PointerEvent)=>{const rect=canvas.getBoundingClientRect();paddle=Math.max(34,Math.min(W-34,((e.clientX-rect.left)/rect.width)*W))};const draw=()=>{ctx.fillStyle='#101114';ctx.fillRect(0,0,W,H);for(let i=0;i<bricks.length;i++){if(!bricks[i])continue;const col=i%7,row=Math.floor(i/7),bx=12+col*50,by=22+row*22;ctx.fillStyle=row%2?'#b6adff':'#fff';ctx.fillRect(bx,by,43,15)}ctx.fillStyle='#fff';ctx.fillRect(paddle-32,H-20,64,7);ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fill()};const loop=()=>{draw();if(gameRef.current.running){if(keys.left)paddle-=6;if(keys.right)paddle+=6;paddle=Math.max(34,Math.min(W-34,paddle));x+=vx;y+=vy;if(x<5||x>W-5)vx=-vx;if(y<5)vy=-vy;if(y>H-30&&x>paddle-38&&x<paddle+38)vy=-Math.abs(vy);for(let i=0;i<bricks.length;i++){if(!bricks[i])continue;const col=i%7,row=Math.floor(i/7),bx=12+col*50,by=22+row*22;if(x>bx&&x<bx+43&&y>by&&y<by+15){bricks[i]=false;vy=-vy;gameRef.current.score+=1;setScore(gameRef.current.score);break}}if(y>H+10){gameRef.current.running=false;setRunning(false)}if(gameRef.current.score===bricks.length){gameRef.current.running=false;setRunning(false)}}raf=requestAnimationFrame(loop)};draw();addEventListener('keydown',e=>onKey(e,true));addEventListener('keyup',e=>onKey(e,false));canvas.addEventListener('pointermove',onMove);return()=>{cancelAnimationFrame(raf);removeEventListener('keydown',e=>onKey(e,true));removeEventListener('keyup',e=>onKey(e,false));canvas.removeEventListener('pointermove',onMove)}},[]);const start=()=>{gameRef.current.running=true;setRunning(true)};return <div className="pf-game-box"><div className="pf-game-head"><span>ARKANOID / NEXUM</span><b>{String(score).padStart(2,'0')}</b></div><canvas ref={canvasRef} width="360" height="260"/><div className="pf-game-controls"><span>{language==='ru'?'← → или ведите пальцем':'← → or move your finger'}</span><button type="button" onClick={start}>{running?(language==='ru'?'ИГРА ИДЁТ':'RUNNING'):(language==='ru'?'ИГРАТЬ':'PLAY')} <ArrowRight size={14}/></button></div></div>}
function PortfolioDetail({language,id}:{language:Language;id:string}){const r=ru(language),item=portfolioItems.find(x=>x.id===id);if(!item)return <NotFound language={language}/>;return <main className="nx-detail pf-detail"><button onClick={()=>go('#portfolio')} className="nx-back">← {r?'Портфолио':'Portfolio'}</button><div className="nx-detail-grid"><div><small>{item.kind} / INTERACTIVE CASE</small><h1>{r?item.ru:item.title}</h1><p>{r?item.ruDesc:item.desc}</p><button className="nx-btn dark" onClick={()=>go('#start')}>{r?'Сделать похожий':'Build something similar'} <ArrowUpRight/></button></div><DemoSite type={item.type}/></div></main>}
\nfunction NotFound({language}:{language:Language}){return <main className="nx-auth"><div className="nx-auth-card"><small>404</small><h1>{ru(language)?'Не найдено':'Not found'}</h1><button className="nx-btn dark" onClick={()=>go('#')}>NEXUM <ArrowRight/></button></div></main>}
export default function PlatformRouter({language}:{language:Language}){const p=(location.hash||'#').split('?')[0];if(p==='#'||p==='')return <Home language={language}/>;if(p==='#services')return <Services language={language}/>;if(p==='#projects')return <Projects language={language}/>;if(p==='#reviews')return <Reviews language={language}/>;if(p==='#portfolio')return <Portfolio language={language}/>;if(p.startsWith('#portfolio/'))return <PortfolioDetail language={language} id={p.split('/')[1]||''}/>;if(p==='#start')return <Start language={language}/>;if(p==='#login'||p==='#register')return <Auth language={language} mode={p==='#login'?'login':'register'}/>;if(p.startsWith('#service/'))return <ServicePage language={language} id={p.split('/')[1]||''}/>;if(p.startsWith('#project/'))return <ProjectPage language={language} id={p.split('/')[1]||''}/>;return <NotFound language={language}/>}
