import {ArrowLeft,ArrowRight,Check,Paperclip,Send,ShieldCheck,Sparkles} from 'lucide-react'
import {useState} from 'react'
import QuoteRail from './QuoteRail'
type Language='ru'|'en'
type FormState={direction:string;stage:string;budget:string;timeline:string;contact:string;company:string;brief:string;features:string[];source:string;files:string[]}
const directions={ru:['Сайт / digital experience','Web-приложение / SaaS','AI-система / AI-агент','CRM / Dashboard','Marketplace / платформа','Мобильное приложение','Автоматизация / интеграции','Поддержка и развитие','Не знаю — нужна консультация'],en:['Website / digital experience','Web app / SaaS','AI system / AI agent','CRM / Dashboard','Marketplace / platform','Mobile application','Automation / integrations','Support & development','Not sure — advise me']}
const features={ru:['UX / UI дизайн','Брендинг и визуальная система','Авторизация и роли','Платежи','AI / LLM','Чаты и коммуникации','Карты / геолокация','CRM / аналитика','Интеграции API','Админ-панель','Мобильная версия','Другое'],en:['UX / UI design','Branding & visual system','Auth & roles','Payments','AI / LLM','Chat & communication','Maps / geolocation','CRM / analytics','API integrations','Admin panel','Mobile version','Other']}
export default function StartProjectPage({language}:{language:Language}){
 const ru=language==='ru'
 const [step,setStep]=useState(1),[submitted,setSubmitted]=useState(false)
 const [form,setForm]=useState<FormState>({direction:'',stage:'',budget:'',timeline:'',contact:'',company:'',brief:'',features:[],source:'',files:[]})
 const set=(key:keyof FormState,value:string)=>setForm(f=>({...f,[key]:value}))
 const toggle=(v:string)=>setForm(f=>({...f,features:f.features.includes(v)?f.features.filter(x=>x!==v):[...f.features,v]}))
 const valid=step===1?!!form.direction:step===2?!!form.brief:!!form.contact
 const next=()=>valid&&setStep(s=>Math.min(3,s+1))
 const back=()=>setStep(s=>Math.max(1,s-1))
 const submit=(e:React.FormEvent)=>{e.preventDefault();if(valid)setSubmitted(true)}
 if(submitted)return <main className="subpage start-page"><section className="start-success-page"><div className="start-success-orb"><Sparkles/></div><small>PROJECT / RECEIVED</small><h1>{ru?'Задача принята.':'Brief received.'}</h1><p>{ru?'Мы получили вводные. Следующий шаг — изучить задачу и вернуться с вопросами, подходом или предложением по разработке.':'We have the brief. Next step is a review followed by questions, an approach or a development proposal.'}</p><div className="start-success-meta"><span><Check/> {ru?'Бриф сохранён':'Brief captured'}</span><span><ShieldCheck/> NDA при необходимости</span></div><button onClick={()=>{setSubmitted(false);setStep(1)}}>{ru?'Создать ещё один brief':'Create another brief'} <ArrowRight size={15}/></button></section></main>
 return <main className="subpage start-page">
  <section className="start-hero-extended"><div><small>04 / START PROJECT</small><h1>{ru?<>Запустим<br/><i>проект.</i></>:<>Start a<br/><i>project.</i></>}</h1></div><div className="start-hero-side"><span>PROJECT INTAKE</span><p>{ru?'Не нужно знать техническое задание. Расскажите, что хотите получить — остальное разложим по этапам.':'You do not need a technical specification. Tell us what you want to build; we will structure the next steps.'}</p><div className="start-trust"><ShieldCheck size={16}/><span>{ru?'NDA · конфиденциальность · без обязательств':'NDA · confidentiality · no commitment'}</span></div></div></section>
  <section className="brief-workspace">
   <aside className="brief-sidebar"><div className="brief-progress"><span className={step>=1?'active':''}>01</span><i className={step>1?'done':''}/><span className={step>=2?'active':''}>02</span><i className={step>2?'done':''}/><span className={step>=3?'active':''}>03</span></div><div className="brief-sidebar-copy"><small>HOW IT WORKS</small><h3>{ru?'От идеи<br/>к системе.':'From idea<br/>to system.'}</h3><p>{ru?'Сначала определим продукт. Затем соберём требования, оценим объём и предложим понятный следующий шаг.':'First we define the product, then scope it, estimate the work and propose a clear next step.'}</p></div></aside>
   <form className="brief-card brief-card-extended" onSubmit={submit}>
    <div className="brief-step-head"><div><small>STEP 0{step}</small><h2>{step===1?(ru?'Что создаём?':'What are we building?'):step===2?(ru?'Расскажите о задаче.':'Tell us about the task.'):(ru?'Контакты и запуск.':'Contact & launch.')}</h2></div><span>{step} / 3</span></div>
    {step===1&&<div className="brief-fields"><Field title={ru?'Направление':'Direction'} required><div className="choice-grid">{directions[language==='ru'?'ru':'en'].map((v,i)=><button type="button" className={form.direction===v?'selected':''} key={v} onClick={()=>set('direction',v)}>{String(i+1).padStart(2,'0')}<b>{v}</b>{form.direction===v&&<Check/>}</button>)}</div></Field><Field title={ru?'На каком этапе вы сейчас?':'Current stage'}><div className="choice-row">{(ru?['Идея','Есть дизайн','Есть MVP','Нужно развитие','Есть готовый продукт']:['Idea','Design ready','MVP ready','Need growth','Existing product']).map(v=><button type="button" className={form.stage===v?'selected':''} key={v} onClick={()=>set('stage',v)}>{v}</button>)}</div></Field></div>}
    {step===2&&<div className="brief-fields"><Field title={ru?'Что нужно получить?':'What do you need?'} required><textarea value={form.brief} onChange={e=>set('brief',e.target.value)} rows={6} placeholder={ru?'Опишите продукт, пользователей, задачу и желаемый результат. Можно простыми словами.':'Describe the product, users, problem and desired outcome. Plain language is fine.'}/></Field><Field title={ru?'Что важно предусмотреть?':'What should be included?'}><div className="feature-grid">{features[language==='ru'?'ru':'en'].map(v=><button type="button" className={form.features.includes(v)?'selected':''} key={v} onClick={()=>toggle(v)}>{form.features.includes(v)&&<Check size={13}/>} {v}</button>)}</div></Field><div className="brief-two-col"><Field title={ru?'Ориентир бюджета':'Budget range'}><select value={form.budget} onChange={e=>set('budget',e.target.value)}><option value="">—</option>{(ru?['до 150 тыс. ₽','150–300 тыс. ₽','300–700 тыс. ₽','700 тыс. – 1.5 млн ₽','1.5 млн ₽ +','Нужна оценка']:['under €2k','€2–4k','€4–9k','€9–18k','€18k +','Need an estimate']).map(v=><option key={v}>{v}</option>)}</select></Field><Field title={ru?'Желаемый срок':'Timeline'}><select value={form.timeline} onChange={e=>set('timeline',e.target.value)}><option value="">—</option>{(ru?['До 1 месяца','1–2 месяца','2–4 месяца','Без жёсткого срока']:['Under 1 month','1–2 months','2–4 months','No hard deadline']).map(v=><option key={v}>{v}</option>)}</select></Field></div></div>}
    {step===3&&<div className="brief-fields"><div className="brief-two-col"><Field title={ru?'Как к вам обращаться?':'Your name / contact'} required><input value={form.contact} onChange={e=>set('contact',e.target.value)} required placeholder={ru?'Имя · Telegram · email · телефон':'Name · Telegram · email · phone'}/></Field><Field title={ru?'Компания':'Company'}><input value={form.company} onChange={e=>set('company',e.target.value)} placeholder={ru?'Необязательно':'Optional'}/></Field></div><Field title={ru?'Откуда узнали о NEXUM?':'How did you find NEXUM?'}><div className="choice-row">{(ru?['Поиск','Telegram','Рекомендация','Портфолио','Другое']:['Search','Telegram','Referral','Portfolio','Other']).map(v=><button type="button" className={form.source===v?'selected':''} key={v} onClick={()=>set('source',v)}>{v}</button>)}</div></Field><Field title={ru?'Материалы проекта':'Project materials'}><button type="button" className="file-drop" onClick={()=>setForm(f=>({...f,files:[...f.files,'project-material']}))}><Paperclip size={16}/><span>{form.files.length?form.files.length+' '+(ru?'файл добавлен':'file added'):(ru?'Добавить файл или ссылку':'Add a file or link')}</span><ArrowRight size={14}/></button></Field><div className="brief-review"><small>PROJECT SUMMARY</small><b>{form.direction||'—'}</b><span>{form.stage||'—'} · {form.budget||'—'} · {form.timeline||'—'}</span><p>{form.brief||'—'}</p></div></div>}
    <div className="brief-bottom"><div>{step>1&&<button type="button" className="brief-back" onClick={back}><ArrowLeft size={14}/>{ru?'Назад':'Back'}</button>}<span className="brief-required">{ru?'* обязательные поля':'* required fields'}</span></div>{step<3?<button type="button" disabled={!valid} onClick={next}>{ru?'Продолжить':'Continue'} <ArrowRight size={15}/></button>:<button type="submit" disabled={!valid}>{ru?'Отправить проект':'Send project'} <Send size={14}/></button>}</div>
    <div className="brief-privacy"><ShieldCheck size={14}/>{ru?'Контактные данные используются только для связи по проекту.':'Contact details are used only for project communication.'}</div>
   </form>
  </section>
  <QuoteRail language={language} section="PROJECT SIGNAL"/>
 </main>
}
function Field({title,required,children}:{title:string;required?:boolean;children:React.ReactNode}){return <label className="brief-field"><span>{title}{required&&<em> *</em>}</span>{children}</label>}
