import {useEffect,useState} from 'react';import {ArrowDown,ArrowUpRight,Mail,Send} from 'lucide-react';import Header from './components/Header';import SectionLabel from './components/SectionLabel';import ProductMockup from './components/ProductMockup';import WorkCard from './components/WorkCard';import CaseStudy from './components/CaseStudy';import MarketplaceShowcase from './components/MarketplaceShowcase';import MarketplacePage from './components/MarketplacePage';import {history,process,services,tech,works} from './data/content'

export type Language='ru'|'en'

function App(){
 const[path,setPath]=useState(location.hash)
 const[language,setLanguage]=useState<Language>(()=>{try{return localStorage.getItem('nexum-language')==='en'?'en':'ru'}catch{return'ru'}})
 useEffect(()=>{const onHash=()=>setPath(location.hash);addEventListener('hashchange',onHash);return()=>removeEventListener('hashchange',onHash)},[])
 useEffect(()=>{try{localStorage.setItem('nexum-language',language)}catch{}},[language])
 const ru=language==='ru'
 const scroll=(id:string)=>document.querySelector(id)?.scrollIntoView({behavior:'smooth'})
 if(path==='#marketplace') return <><Header language={language} onLanguageChange={setLanguage}/><MarketplacePage language={language}/></>
 if(path.startsWith('#case/')) return <><Header language={language} onLanguageChange={setLanguage}/><CaseStudy id={path.split('/')[1]} language={language}/></>
 return <><Header language={language} onLanguageChange={setLanguage}/><main>
  <MarketplaceShowcase language={language}/>
  <section className="hero" id="top"><div className="hero-copy"><p className="kicker">{ru?'ЦИФРОВАЯ / ПРОДУКТОВАЯ СТУДИЯ':'DIGITAL / PRODUCT STUDIO'}</p><h1>{ru?'Создаём продукты, которыми хочется пользоваться.':'We create products people want to use.'}</h1><div className="hero-bottom"><p>{ru?'Сайты, приложения, AI-решения и автоматизация бизнеса — от идеи до работающего продукта.':'Websites, applications, AI solutions and business automation — from idea to a working product.'}</p><button className="primary" onClick={()=>scroll('#contact')}>{ru?'Обсудить проект':'Start a project'} <ArrowUpRight size={17}/></button><button className="text-btn" onClick={()=>scroll('#work')}>{ru?'Посмотреть работы':'View our work'} <ArrowDown size={15}/></button></div></div><div className="hero-visual"><ProductMockup kind="dashboard" large language={language}/><span className="editorial-tag">{ru?'ИЗБРАННАЯ РАБОТА':'SELECTED WORK'}<br/><b>01 / 06</b></span></div></section>
  <section className="manifesto"><div className="manifesto-mark">N.</div><div><p>{ru?'Мы не собираем сайты по шаблону.':'We do not build websites from templates.'}</p><h2>{ru?'Мы проектируем цифровые продукты вокруг людей, задач и результата.':'We design digital products around people, problems and outcomes.'}</h2></div></section>
  <section id="services" className="section services"><SectionLabel n="01" label={ru?'УСЛУГИ':'SERVICES'}/><div className="section-intro"><h2>{ru?'Что мы создаём':'What we create'}</h2><p>{ru?'От первого экрана до сложной операционной системы бизнеса — одна команда для продукта целиком.':'From the first screen to a complex business operating system — one team for the whole product.'}</p></div><div className="service-list">{services.map(s=><article key={s.n} className="service-row" tabIndex={0}>
<span className="service-number">{s.n}</span>
<div className="service-main"><div className="service-heading"><h3>{ru?s.ruTitle:s.title}</h3><span className="service-type">{ru?s.ruType:s.type}</span></div><p>{ru?s.ruText:s.text}</p><div className="service-tags">{(ru?s.ruTags:s.tags).map(tag=><span key={tag}>{tag}</span>)}</div></div>
<ArrowUpRight className="service-arrow"/>
</article>)}</div></section>
  <section id="work" className="section work"><SectionLabel n="02" label={ru?'РАБОТЫ':'WORK'}/><div className="section-intro"><h2>{ru?'Избранные работы':'Selected work'}</h2><p>{ru?'Концепции и продуктовые системы, собранные вокруг реальных сценариев использования.':'Concepts and product systems built around real usage scenarios.'}</p></div><div className="work-grid">{works.map((w,i)=><WorkCard key={w.id} work={w} index={i} language={language}/>)}</div></section>
  <section id="history" className="section history-section"><SectionLabel n="02A" label={ru?'ИСТОРИЯ':'HISTORY'}/><div className="section-intro"><h2>{ru?'Как мы к этому пришли':'How we got here'}</h2><p>{ru?'Путь от первых цифровых продуктов к собственной экосистеме Nexum.':'From the first digital products to the Nexum ecosystem.'}</p></div><div className="history-list">{history.map(item=><article key={item.id}><span>{ru?item.ruYear:item.enYear}</span><div><h3>{ru?item.ruTitle:item.enTitle}</h3><p>{ru?item.ruText:item.enText}</p></div></article>)}</div></section>
  <section id="process" className="section process-section"><SectionLabel n="03" label={ru?'ПРОЦЕСС':'PROCESS'}/><div className="section-intro"><h2>{ru?'От идеи до':'From idea to'}<br/><i>{ru?'работающего продукта.':'a working product.'}</i></h2></div><div className="process-list">{process.map(([n,t,d,ruT,ruD])=><article key={n}><span>{n}</span><h3>{ru?ruT:t}</h3><p>{ru?ruD:d}</p></article>)}</div></section>
  <section id="technology" className="section tech-section"><SectionLabel n="04" label={ru?'ТЕХНОЛОГИИ':'TECHNOLOGY'}/><div className="tech-layout"><div><h2>{ru?'Технологический':'Technology'}<br/><i>{ru?'стек.':'stack.'}</i></h2><p>{ru?'Инструменты выбираются под задачу. Не ради моды, а ради скорости, качества и возможности продукта расти.':'Tools are chosen for the task — for speed, quality and the ability to scale.'}</p></div><div className="tech-list">{tech.map((t,i)=><div key={t}><span>0{i+1}</span><b>{t}</b><ArrowUpRight size={17}/></div>)}</div></div></section>
  <section id="ai" className="ai-section"><div className="ai-copy"><SectionLabel n="—" label={ru?'AI / СЛОЙ ПРОДУКТА':'AI / PRODUCT LAYER'}/><h2>{ru?'AI — не функция.':'AI is not a feature.'}<br/><i>{ru?'Это новый слой продукта.':'It is a new product layer.'}</i></h2><p>{ru?'Ассистенты, агенты и автоматизация встраиваются прямо в рабочие процессы: анализируют данные, отвечают, создают и выполняют действия.':'Assistants, agents and automation become part of the workflow: they analyze data, answer questions, create and execute actions.'}</p><button className="light-btn" onClick={()=>scroll('#contact')}>{ru?'Создать продукт с AI':'Build with AI'} <ArrowUpRight size={16}/></button></div><div className="ai-visual"><ProductMockup kind="ai" large language={language}/></div></section>
  <section id="about" className="section about"><SectionLabel n="05" label={ru?'О НАС':'ABOUT'}/><div className="about-layout"><h2>{ru?'Не просто красивый сайт.':'Not just a beautiful website.'}<br/><i>{ru?'Работающий инструмент.':'A working tool.'}</i></h2><div><p>{ru?'Мы создаём цифровые продукты для компаний, которым нужен не просто красивый сайт, а работающий инструмент.':'We create digital products for companies that need more than a beautiful website — they need a working tool.'}</p><div className="facts"><span>{ru?'Цифровые продукты':'Digital products'}</span><span>Web</span><span>AI</span><span>{ru?'Автоматизация':'Automation'}</span></div></div></div></section>
  <section id="contact" className="contact"><div className="contact-label">06 / {ru?'КОНТАКТЫ':'CONTACT'}</div><h2>{ru?'Есть идея?':'Have an idea?'}<br/><i>{ru?'Давайте превратим её':'Let’s turn it'}<br/>{ru?'в работающий продукт.':'into a working product.'}</i></h2><a className="contact-button" href="mailto:hello@nexum.agency">{ru?'Обсудить проект':'Start a project'} <ArrowUpRight/></a><div className="contact-links"><a href="mailto:hello@nexum.agency"><Mail size={15}/> hello@nexum.agency</a><a href="#contact"><Send size={15}/> Telegram</a></div></section>
 </main><footer><div className="footer-brand">NEXUM<span>—</span></div><div className="footer-nav">{(ru?['Услуги','Работы','Процесс','О нас','Контакты']:['Services','Work','Process','About','Contact']).map((x,i)=><button key={x} onClick={()=>scroll(['#services','#work','#process','#about','#contact'][i])}>{x}</button>)}</div><span>© 2026 Nexum Digital Agency</span></footer></>}
export default App