import {useEffect,useState} from 'react';import {ArrowDown,ArrowUpRight,Mail,Send} from 'lucide-react';import Header from './components/Header';import SectionLabel from './components/SectionLabel';import ProductMockup from './components/ProductMockup';import WorkCard from './components/WorkCard';import CaseStudy from './components/CaseStudy';import {process,services,tech,works} from './data/content'
function App(){const[path,setPath]=useState(location.hash);useEffect(()=>{const onHash=()=>setPath(location.hash);addEventListener('hashchange',onHash);return()=>removeEventListener('hashchange',onHash)},[]); if(path.startsWith('#case/')) return <><Header/><CaseStudy id={path.split('/')[1]}/></>; const scroll=(id:string)=>document.querySelector(id)?.scrollIntoView({behavior:'smooth'});return <><Header/><main>
<section className="hero" id="top"><div className="hero-copy"><p className="kicker">DIGITAL / PRODUCT STUDIO</p><h1>Создаём цифровые продукты,<br/><i>которыми хочется пользоваться.</i></h1><div className="hero-bottom"><p>Сайты, приложения, AI-решения и автоматизация бизнеса — от идеи до работающего продукта.</p><button className="primary" onClick={()=>scroll('#contact')}>Обсудить проект <ArrowUpRight size={17}/></button><button className="text-btn" onClick={()=>scroll('#work')}>Посмотреть работы <ArrowDown size={15}/></button></div></div><div className="hero-visual"><ProductMockup kind="dashboard" large/><span className="editorial-tag">SELECTED WORK<br/><b>01 / 06</b></span></div></section>
<section className="manifesto"><div className="manifesto-mark">N.</div><div><p>Мы не собираем сайты по шаблону.</p><h2>Мы проектируем цифровые продукты вокруг людей, задач и результата.</h2></div></section>
<section id="services" className="section services"><SectionLabel n="01" label="SERVICES"/><div className="section-intro"><h2>Что мы создаём</h2><p>От первого экрана до сложной операционной системы бизнеса — одна команда для продукта целиком.</p></div><div className="service-list">{services.map(s=><article key={s.n} className="service-row"><span>{s.n}</span><h3>{s.title}</h3><p>{s.text}</p><ArrowUpRight/></article>)}</div></section>
<section id="work" className="section work"><SectionLabel n="02" label="WORK"/><div className="section-intro"><h2>Selected work</h2><p>Концепции и продуктовые системы, собранные вокруг реальных сценариев использования.</p></div><div className="work-grid">{works.map((w,i)=><WorkCard key={w.id} work={w} index={i}/>)}</div></section>
<section id="process" className="section process-section"><SectionLabel n="03" label="PROCESS"/><div className="section-intro"><h2>От идеи до<br/><i>работающего продукта.</i></h2></div><div className="process-list">{process.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="section tech-section"><SectionLabel n="04" label="TECHNOLOGY"/><div className="tech-layout"><div><h2>Technology<br/><i>stack.</i></h2><p>Инструменты выбираются под задачу. Не ради моды, а ради скорости, качества и возможности продукта расти.</p></div><div className="tech-list">{tech.map((t,i)=><div key={t}><span>0{i+1}</span><b>{t}</b><ArrowUpRight size={17}/></div>)}</div></div></section>
<section className="ai-section"><div className="ai-copy"><SectionLabel n="—" label="AI / PRODUCT LAYER"/><h2>AI — не функция.<br/><i>Это новый слой продукта.</i></h2><p>Ассистенты, агенты и автоматизация встраиваются прямо в рабочие процессы: анализируют данные, отвечают, создают и выполняют действия.</p><button className="light-btn" onClick={()=>scroll('#contact')}>Build with AI <ArrowUpRight size={16}/></button></div><div className="ai-visual"><ProductMockup kind="ai" large/></div></section>
<section id="about" className="section about"><SectionLabel n="05" label="ABOUT"/><div className="about-layout"><h2>Не просто красивый сайт.<br/><i>Работающий инструмент.</i></h2><div><p>Мы создаём цифровые продукты для компаний, которым нужен не просто красивый сайт, а работающий инструмент.</p><div className="facts"><span>Digital products</span><span>Web</span><span>AI</span><span>Automation</span></div></div></div></section>
<section id="contact" className="contact"><div className="contact-label">06 / CONTACT</div><h2>Есть идея?<br/><i>Давайте превратим её<br/>в работающий продукт.</i></h2><a className="contact-button" href="mailto:hello@nexum.agency">Обсудить проект <ArrowUpRight/></a><div className="contact-links"><a href="mailto:hello@nexum.agency"><Mail size={15}/> hello@nexum.agency</a><a href="#"><Send size={15}/> Telegram</a></div></section>
</main><footer><div className="footer-brand">NEXUM<span>—</span></div><div className="footer-nav">{['Services','Work','Process','About','Contact'].map(x=><button key={x} onClick={()=>scroll('#'+x.toLowerCase())}>{x}</button>)}</div><span>© 2026 Digital Agency</span></footer></>}
export default App